### ISSUE TITLE
Features of the perfect toy datasets

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltToyData#24]
We recently improved the toy datasets for emissions profile (#19). However there seem to be still some details to improve (https://github.com/2DegreesInvesting/tiltToyData/pull/19#issuecomment-1889276566).

@AnneSchoenauer and @Tilmon, please share your list of required features (for inspiration see the "Features" list in [this item of the changelog](https://2degreesinvesting.github.io/tiltToyData/news/index.html#tilttoydata-0009007-2024-01-11). 
I'll add your list here as a check-box tasklist and create separate issues to address each request.

From conversations in 2DegreesInvesting/tiltToyData#19 I see that we spent a lot of effort trying to ensure the privacy of licensed data. That effort is only necessary if we base our toy datasets in real data. While realism might be valuable it seems important to weight if it's worth the risk of exposing private data, and worth the kind of effort we put in 2DegreesInvesting/tiltToyData#19. If we can indeed sacrifice realism in some sensitive columns, then we may simply populate them with totally fake values.

### `toy_emissions_profile*`

Datasets:

* `toy_emissions_profile_any_companies()`.
* `toy_emissions_profile_products_ecoinvent()`.
* `toy_emissions_profile_upstream_products_ecoinvent()`.

Features:

- [x] Fake `companies_id` (#19).
- [x] Fake `activity_uuid_product_uuid` (#19).
- [x] Random/broken mapping between fake `activity_uuid_product_uuid` and other columns (#19).
- [x] Noisy `*co2_footprint`, jittered to the right by 50%-100% on average (#19).
- [x] Each `activity_uuid_product_uuid` in `*companies` also exist in `co2` (#25).
- [x] Some `activity_uuid_product_uuid` in `co2` don't exist in `*companies` (#25).
- [x] Some `activity_uuid_product_uuid` in `*companies` also exist in `co2` (#25).
- [ ] https://github.com/2DegreesInvesting/tiltToyDataPrivate/issues/11

### `toy_sector_profile*`

- [ ] ...

**Comment by AnneSchoenauer** [comment]
@Tilmon is it fine if you take this as you know better the licenses issues - however let me know if I should give it a trial! :)

**Comment by Tilmon** [comment]
Hi @maurolepore , thanks for this. 

I see following 2 features that are not covered yet: 

- [ ] `ei_input_geography `should have fake values. As @kalashsinghal mentioned here, he's planning on adding the column `ei_input_geography `to the outputs. To avoid the risk that that enables users to identify the unique input, I suggest we create fake geography values. Probably best to make it obvious that they are fake, so what about "tiltland" or "low carbon wonderland"?
- [ ] `input_activity_uuid_product_uuid` should be a fake value, so that users can't identify a unique link between an activity and an input (this link is licensed information). In [this comment](https://github.com/2DegreesInvesting/tiltToyData/pull/19#issuecomment-1888910146) I even suggested, to create an internal mapper between real `input_activity_uuid_product_uuid` and fake IDs which is not public-facing, but now i realize that if we only talk about the toy data, this is not even necessary, as the toy data should look realistic but there is no need that they contain actual "truth" of the real data, right?

**Comment by Tilmon** [comment]
@maurolepore please correct to 

activity_uuid_product_uuid can be reproduced from these columns -- which therefore can't be shared together.

ei_activity_name
ei_reference_name
main_activity
geography

and

input_activity_uuid_product_uuid can be reproduced from these columns -- which therefore can't be shared together.

ei_input_activity_name
ei_input_reference_name
input_main_activity
input_geography

cc' @kalashsinghal

**Comment by kalashsinghal** [comment]
@maurolepore Renaming the columns:

For activity_uuid_product_uuid:

ei_activity_name
input_reference_product_name (There is no reference name for activity_uuid_product_uuid)
main_activity
product_geography

and

For input_activity_uuid_product_uuid:

input_ei_activity_name
input_reference_product_name
main_activity
input_geography

cc' @Tilmon

**Comment by Tilmon** [comment]
Hi @kalashsinghal I just checked[ tiltIndicatorAfter for profile_emissions_upstream](https://2degreesinvesting.github.io/tiltIndicatorAfter/reference/profile_emissions_upstream.html) and the variable is called: `matched_reference_product`

**Comment by Tilmon** [comment]
*That's the output name, not sure how it's called in your input data. But hopefully helps to identify the right column?
